---
- runFlow: ../common/bootstrap.yaml
- openLink: cobalt://compose/advanced
- assertVisible:
    id: e2e-screen-compose__advanced
- tapOn:
    id: e2e-action-compose__advanced-add-layer
- tapOn:
    id: e2e-action-compose__advanced-render
