export const LOG_TAGS = {
  SystemInfo: "SystemInfo",
  LogExport: "LogExport",
  GlobalError: "GlobalError",
  Runtime: "Runtime",
  AppUpdate: "AppUpdate",
  useAutoSolve: "useAutoSolve",
  AutoBackup: "AutoBackup",
  Calendar: "Calendar",
  Converter: "Converter",
  Compose: "Compose",
  Export: "Export",
  FitsFile: "FitsFile",
  FileManager: "FileManager",
  ImageEditor: "ImageEditor",
  Location: "Location",
  MediaLibrary: "MediaLibrary",
  Sessions: "Sessions",
  Stacking: "Stacking",
  AlbumExportSheet: "AlbumExportSheet",
  AlbumExporter: "AlbumExporter",
  Thumbnail: "Thumbnail",
  FitsHeaderWriter: "FitsHeaderWriter",
  BackupService: "BackupService",
  LocalBackup: "LocalBackup",
  OAuthHelper: "OAuthHelper",
  GoogleDriveProvider: "GoogleDriveProvider",
  OneDriveProvider: "OneDriveProvider",
  DropboxProvider: "DropboxProvider",
  WebDAVProvider: "WebDAVProvider",
  AstrometryClient: "AstrometryClient",
  AstrometryService: "AstrometryService",
  SyncToTarget: "SyncToTarget",
  WCSExport: "WCSExport",
  useAstrometry: "useAstrometry",
} as const;

export type LogTag = (typeof LOG_TAGS)[keyof typeof LOG_TAGS];
